name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - src/**
  pull_request:
    branches:
      - main
      - develop
    paths:
      - src/**

jobs:
  test-using-cargo:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: cargo test

  tarpaulin-codecov:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run cargo-tarpaulin
        run: cargo tarpaulin --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml

  clippy-check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
